fix: deduplicate tags
projectcaluma/alexandria pull request #121
Opened 2020-12-08 10:55 UTC by winged

The with_documents_in_category filter can duplicate tags, so we
deduplicate the results upfront.

This is easier here than to apply selectively when the filter is active,
and shouldn't impact performance.

2020-12-08 22:27 UTC, fkm approved these changes

2020-12-09 06:21 UTC, open-dynaMIX requested changes
Awesome!

Just a small nitpick.

2020-12-09 06:21 UTC, open-dynaMIX commented on alexandria/core/tests/test_filters.py
>      assert result["data"][0]["id"] == str(blue.pk)
Can we be sure that the order of the tags in the response is consistent? If not, we should do something like:

```python
assert sorted([t["id"] for t in result["data"]]) == [blue.pk, green.pk]
```

2020-12-09 08:20 UTC, open-dynaMIX commented on alexandria/core/tests/test_filters.py
> +    assert sorted(returned_tags) == sorted(["blue", "green"])
No need to sort `["blue", "green"]` ;)

2020-12-09 08:20 UTC, open-dynaMIX approved these changes

2020-12-09 08:46 UTC, merged