Allow filtering documents with tag synonyms
projectcaluma/alexandria pull request #150
Opened 2021-03-19 14:11 UTC by fugal-dy

This adds the TagSynonymGroup model and extends the
documents tagfilter such that filtering for document
by tag looks for associated synonyms to include.

Issue #133

2021-03-19 14:36 UTC, winged requested changes
Good work so far!

There are a couple of things missing:

* Register the new viewset under **alexandria/core/urls.py**
* Your `black` was a bit overzealous - check the version we use vs. your version

2021-03-20 16:40 UTC, fugal-dy commented on alexandria/core/models.py
> +from django.conf import settings
```suggestion
```
True. Incomplete code cleanup after removing localization that was using `settings.LANGUAGES` for `choices`  and `settings.LANGUAGE_CODE` for `default`

2021-03-21 23:29 UTC, fugal-dy commented
I have applied your inputs, fixed the filter (did not do what it should) and did some cleanup. On top I added an extra test that does not make it past linting though o_0. I need some sleep now, will get back to finishing this later

2021-03-26 11:19 UTC, winged requested changes

2023-11-09 07:48 UTC, Yelinz commented
Seems to have been merged with https://github.com/projectcaluma/alexandria/pull/256 already, reopen if not

2023-11-09 07:48 UTC, closed without merging