feat: use dgap instead of custom visibilities and permissions
projectcaluma/alexandria pull request #289
Opened 2023-05-04 12:10 UTC by Yelinz

2023-11-10 17:48 UTC, winged requested changes
Nice, looking good! However I think you'll need to mark this as breaking, as it will require changes in the deployments

2023-11-15 08:47 UTC, winged approved these changes

2023-11-15 13:11 UTC, Yelinz commented
Struggled with updating the snapshots, code did not change.

2023-11-15 16:36 UTC, Yelinz commented
Will merge it later, please do not just merge this. Thx

2023-11-17 09:09 UTC, merged